In [0]:
%matplotlib notebook
# %autosave 10
# %lsmagic
# print(plt.style.available)

import numpy as np
from pylab import *
from matplotlib import gridspec
from matplotlib import pyplot as plt
import subprocess

#<span class="mark">format</span>

In [0]:
# https://pyformat.info/

In [0]:
i=1/3
print("test bir ki bir ki: {:>10}".format(i))

test bir ki bir ki: 0.3333333333333333


In [0]:
'{:>10}'.format('test')

'      test'

In [0]:
'{:10}'.format('test')

'test      '

In [0]:
#You are able to choose the padding character:
'{:_<10}'.format('test')

'test______'

In [0]:
#And also center align values:
'{:^10}'.format('test')

'   test   '

In [0]:
# Truncating long strings
'{:.5}'.format('xylophone')

'xylop'

In [0]:
'{:f}'.format(3.141592653589793)

'3.141593'

In [0]:
'{:4d}'.format(42)

'  42'

In [0]:
'{:06.2f}'.format(3.141592653589793)

'003.14'

In [0]:
'{:04d}'.format(42)

'0042'

In [0]:
'{:+d}'.format(42)

'+42'

In [0]:
'{: d}'.format((- 23))

'-23'

In [0]:
'{:=5d}'.format((- 23))

'-  23'

In [0]:
data = {'first': 'Hodor', 'last': 'Hodor!'}

'{first} {last}'.format(**data)

'Hodor Hodor!'

In [0]:
person = {'first': 'Jean-Luc', 'last': 'Picard'}

'{p[first]} {p[last]}'.format(p=person)

'Jean-Luc Picard'

In [0]:
data = [4, 8, 15, 16, 23, 42]
'{d[4]} {d[5]}'.format(d=data)

'23 42'

In [0]:
from datetime import datetime

'{:%Y-%m-%d %H:%M}'.format(datetime(2001, 2, 3, 4, 5))

'2001-02-03 04:05'

In [0]:
'{:.{prec}} = {:.{prec}f}'.format('Gibberish', 2.7182, prec=3)

'Gib = 2.718'

In [0]:
from datetime import datetime
dt = datetime(2001, 2, 3, 4, 5)

'{:{dfmt} {tfmt}}'.format(dt, dfmt='%Y-%m-%d', tfmt='%H:%M')

'2001-02-03 04:05'

#<span class="mark">permutation, combination, itertools</span>

In [0]:
from itertools import product, combinations, permutations

# product('ABCD', repeat=2)  ---  AA AB AC AD BA BB BC BD CA CB CC CD DA DB DC DD
# permutations('ABCD', 2)    ---  AB AC AD BA BC BD CA CB CD DA DB DC
# combinations('ABCD', 2)    ---  AB AC AD BC BD CD

# combinations_with_replacement('ABCD', 2) --- AA AB AC AD BB BC BD CC CD DD

for i in product('ABCD', repeat=2):
    print(i)

('A', 'A')
('A', 'B')
('A', 'C')
('A', 'D')
('B', 'A')
('B', 'B')
('B', 'C')
('B', 'D')
('C', 'A')
('C', 'B')
('C', 'C')
('C', 'D')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'D')


In [0]:
a = [1, 2]
b = [-1, 0, 1]

np.array(list(product(a, b)))

array([[ 1, -1],
       [ 1,  0],
       [ 1,  1],
       [ 2, -1],
       [ 2,  0],
       [ 2,  1]])

In [0]:
r = [0, 1]
np.array(list(product(r, r, r)))

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [0]:
r = [0, 1]

for s, e in combinations(np.array(list(product(r, r, r))), 2):
    if np.sum(np.abs(s-e)) == r[1]-r[0]:
        print(s,e)
#         print(*zip(s, e))


[0 0 0] [0 0 1]
[0 0 0] [0 1 0]
[0 0 0] [1 0 0]
[0 0 1] [0 1 1]
[0 0 1] [1 0 1]
[0 1 0] [0 1 1]
[0 1 0] [1 1 0]
[0 1 1] [1 1 1]
[1 0 0] [1 0 1]
[1 0 0] [1 1 0]
[1 0 1] [1 1 1]
[1 1 0] [1 1 1]


In [0]:
r = [0, 1]

for s, e in combinations(np.array(list(product(r, r, r))), 2):
    if np.sum(np.abs(s-e)) == r[1]-r[0]:
#         print(s,e)
        print(*zip(s, e))

(0, 0) (0, 0) (0, 1)
(0, 0) (0, 1) (0, 0)
(0, 1) (0, 0) (0, 0)
(0, 0) (0, 1) (1, 1)
(0, 1) (0, 0) (1, 1)
(0, 0) (1, 1) (0, 1)
(0, 1) (1, 1) (0, 0)
(0, 1) (1, 1) (1, 1)
(1, 1) (0, 0) (0, 1)
(1, 1) (0, 1) (0, 0)
(1, 1) (0, 1) (1, 1)
(1, 1) (1, 1) (0, 1)


In [0]:
r = [0, 1, 2, 3, 4, 5 ,6 ,7 ,8 ,9]

ofile = open('tmp1.dat', 'w')
o=[]
for i in combinations(r, 6):
    t = [0,0,0,0,0,0,0,0,0,0]
    for j in range(len(i)):
        t[i[j]]=1
    ofile.write('MAGMOM = {d[0]} {d[1]} {d[2]} {d[3]} {d[4]} {d[5]} {d[6]} {d[7]} {d[8]} {d[9]} 24*0 14*0 \n'.format(d=t))
ofile.close()    


In [0]:
    f = open('positions.dat', 'w')            
    for i in pos_new:
        f.write('  %13.6f%13.6f%13.6f   %2d  %2d  %3s  %6.3f\n' % (i[0], i[1], i[2], i[3], i[4], i[5], i[6]))        
    f.close()